### PR TITLE
Use images from images-rb 

### PR DESCRIPTION
**Pull request by TonyCTHsu**
**What does this PR do?**

Use images from images-rb

### CODE REVIEW

**Comment by anmarchenko** [comment]
@TonyCTHsu thank you!!

**Review by anmarchenko — APPROVED** [review]

**Comment by ivoanjo** [comment]
Should we maybe delete the Dockerfiles in https://github.com/DataDog/dd-trace-rb/tree/master/.circleci/images/primary to avoid any confusion?

**Comment by TonyCTHsu** [comment]
>Should we maybe delete the Dockerfiles in https://github.com/DataDog/dd-trace-rb/tree/master/.circleci/images/primary to avoid any confusion?

For migration, we can swap out all the images used for unit tests theoretically. But those images are used by integration tests in `dd-trace-rb`. We need to change how we conduct integration tests before deleting those images.

**Comment by ivoanjo** [comment]
>  But those images are used by integration tests in dd-trace-rb.

Wait, isn't the integration test images (in CircleCI) what we're changing here? Or do you maybe mean the images we use in `docker-compose.yml` for local development?

**Comment by ivoanjo** [comment]
Update: I totally thought this PR was on the dd-trace-rb repo. My comments make no sense in the scope of datadog-ci-rb. Sorry for the confusion >_>

**Pull request merged**
